### ISSUE TITLE
README.md 這一段的作用看不太懂如何做

### ISSUE THREAD

**Issue by yuchih** [m0neyball/webstorm-config#1]
```json
"scripts": {
  "lint": "eslint yourDirectory"
}
```

@futureappworker 我是直接打 `.`  root folder 就 ok 了嗎?

```json
"scripts": {
  "lint": "."
}
```

**Comment by futureappworker** [comment]
yourDirectory 指你想 ESLint 的目錄
比如我們想 ESLint src 目錄就好的話
"scripts": {
  "lint": "eslint src"
}
即可

2016-04-06 14:21 GMT+08:00 youzi.hsiao <notifications@github.com>:

**Comment by yuchih** [comment]
@futureappworker 了解了 類似 npm run `build` 那區段一樣

**Comment by futureappworker** [comment]
Yes
2016/4/6 下午2:46於 "youzi.hsiao" <notifications@github.com>寫道：

**Comment by yuchih** [comment]
@futureappworker 已了解
